[package]
name = "mypass"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15"
eframe = "0.22"
env_logger = "0.10"
keepass = { version = "0.6", git = "https://github.com/ssrlive/keepass-rs.git", branch = "patch-1" }
log = "0.4"
thiserror = "1.0"

[dev-dependencies]
